name: plan_pusulasi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  hexcolor: ^3.0.1
  intl: ^0.17.0
  shared_preferences: ^2.2.2
  crypto: ^3.0.3

  # Local database
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/logo1.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "lib/assets/images/logo1.png"
    background_color: "#FFFFFF"
    theme_color: "#25052B"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/images/logo.png
    - lib/assets/images/logo1.png
    - lib/assets/images/header.png
